//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Station", Namespace = "http://schemas.datacontract.org/2004/07/ProxyCacheServer")]
    public partial class Station : object
    {

        private ServiceReference.AddressPoint AddressField;

        private string ContractNameField;

        private string NameField;

        private int NbBikesField;

        private int NbSpotsField;

        private int NumberField;

        private int TotSpotsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.AddressPoint Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractName
        {
            get
            {
                return this.ContractNameField;
            }
            set
            {
                this.ContractNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbBikes
        {
            get
            {
                return this.NbBikesField;
            }
            set
            {
                this.NbBikesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbSpots
        {
            get
            {
                return this.NbSpotsField;
            }
            set
            {
                this.NbSpotsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotSpots
        {
            get
            {
                return this.TotSpotsField;
            }
            set
            {
                this.TotSpotsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AddressPoint", Namespace = "http://schemas.datacontract.org/2004/07/ProxyCacheServer")]
    public partial class AddressPoint : object
    {

        private string LabelField;

        private double LatField;

        private double LonField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                this.LabelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lat
        {
            get
            {
                return this.LatField;
            }
            set
            {
                this.LatField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lon
        {
            get
            {
                return this.LonField;
            }
            set
            {
                this.LonField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Contracts", Namespace = "http://schemas.datacontract.org/2004/07/ProxyCacheServer")]
    public partial class Contracts : object
    {

        private ServiceReference.Contract[] ItemsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Contract[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Contract", Namespace = "http://schemas.datacontract.org/2004/07/ProxyCacheServer")]
    public partial class Contract : object
    {

        private string[] CitiesField;

        private string ContractNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Cities
        {
            get
            {
                return this.CitiesField;
            }
            set
            {
                this.CitiesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractName
        {
            get
            {
                return this.ContractNameField;
            }
            set
            {
                this.ContractNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference.IProxyCacheService")]
    public interface IProxyCacheService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IProxyCacheService/GetStations", ReplyAction = "http://tempuri.org/IProxyCacheService/GetStationsResponse")]
        System.Threading.Tasks.Task<ServiceReference.Station[]> GetStationsAsync(string contract);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IProxyCacheService/GetContracts", ReplyAction = "http://tempuri.org/IProxyCacheService/GetContractsResponse")]
        System.Threading.Tasks.Task<ServiceReference.Contracts> GetContractsAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IProxyCacheService/GetRoute", ReplyAction = "http://tempuri.org/IProxyCacheService/GetRouteResponse")]
        System.Threading.Tasks.Task<string> GetRouteAsync(bool isBike, ServiceReference.AddressPoint from, ServiceReference.AddressPoint to);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IProxyCacheServiceChannel : ServiceReference.IProxyCacheService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ProxyCacheServiceClient : System.ServiceModel.ClientBase<ServiceReference.IProxyCacheService>, ServiceReference.IProxyCacheService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ProxyCacheServiceClient() :
                base(ProxyCacheServiceClient.GetDefaultBinding(), ProxyCacheServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IProxyCacheService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ProxyCacheServiceClient(EndpointConfiguration endpointConfiguration) :
                base(ProxyCacheServiceClient.GetBindingForEndpoint(endpointConfiguration), ProxyCacheServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ProxyCacheServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(ProxyCacheServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ProxyCacheServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(ProxyCacheServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ProxyCacheServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<ServiceReference.Station[]> GetStationsAsync(string contract)
        {
            return base.Channel.GetStationsAsync(contract);
        }

        public System.Threading.Tasks.Task<ServiceReference.Contracts> GetContractsAsync()
        {
            return base.Channel.GetContractsAsync();
        }

        public System.Threading.Tasks.Task<string> GetRouteAsync(bool isBike, ServiceReference.AddressPoint from, ServiceReference.AddressPoint to)
        {
            return base.Channel.GetRouteAsync(isBike, from, to);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProxyCacheService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProxyCacheService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/ProxyCacheService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProxyCacheServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IProxyCacheService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProxyCacheServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IProxyCacheService);
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_IProxyCacheService,
        }
    }
}
